sudo: required

language: go

go_import_path: github.com/orange-cloudfoundry/credhub_exporter

services:
  - docker


# jobs:
#   include:
#     - stage: Run tests
#       script: make test

#     - stage: Build docker image
#       env:
#         - DOCKER_IMAGE_NAME=psycofdj/credhub-exporter
#       script:
#         - make crossbuild
#         - ln -s .build/linux-amd64/credhub_exporter credhub_exporter
#         - |
#           if [ -n "$TRAVIS_TAG" ]; then
#             make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$TRAVIS_TAG
#           else
#             make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
#           fi
#         - |
#           if [[ "$TRAVIS_TAG" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
#             docker tag "$DOCKER_IMAGE_NAME:$TRAVIS_TAG" "$DOCKER_IMAGE_NAME:latest"
#           fi
#         - docker images
#         - |
#           if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
#             docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
#             docker push $DOCKER_IMAGE_NAME
#           fi
